Port osu!lazer tutorial
osu-atri/lazer-wiki pull request #1
Opened 2024-07-18 08:45 UTC by CloneWith

Changes:

- Divide topics into individual articles
- Port images to repo
- Fix blocks and lists

2024-07-18 16:19 UTC, CloneWith commented
Oh yeah, what big work you've done! That's awesome 👍

By the way, I've temporarily commented out the Sidebar reference in README, since it would cause errors until we define one for that in the main repo.

2024-07-18 16:47 UTC, NaughtyChas commented
> Oh yeah, what big work you've done! That's awesome 👍
> 
> By the way, I've temporarily commented out the Sidebar reference in README, since it would cause errors until we define one for that in the main repo.

noted in the PR in main repo. The test-build process should be okay if this PR gets merged.

2024-07-18 16:49 UTC, NaughtyChas requested changes

2024-07-18 16:49 UTC, NaughtyChas commented on README.md
> +# displayed_sidebar: lazerSidebar
Remove this comment so we can merge this PR.

2024-07-18 23:27 UTC, CloneWith commented
Saw that just now lol

2024-07-19 03:03 UTC, NaughtyChas approved these changes

2024-07-19 03:03 UTC, NaughtyChas commented
Ready to be merged

2024-07-19 03:04 UTC, merged